# Generated by Django 3.0a1 on 2019-10-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artice_title', models.CharField(max_length=200)),
                ('artice_text', models.TextField()),
                ('artice_date', models.DateTimeField()),
                ('artice_likes', models.IntegerField()),
            ],
            options={
                'db_table': 'artice',
            },
        ),
    ]
